name: Deploy Java App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Dar permissão de execução ao Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build Gradle
        run: ./gradlew clean build -x test
        working-directory: ./  # se seu build.gradle estiver na raiz do repo

      - name: Build Docker image
        run: docker build -t minha-app .

      - name: Copiar docker-compose.yml para a VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/app"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            cd ~/app
            docker-compose down
            docker-compose up -d --build
