name: Deploy OLX Crawler

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Dar permissão de execução ao Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build Gradle
        run: ./gradlew clean build -x test
        working-directory: ./   # ajuste se seu build.gradle estiver em subpasta

      - name: Build Docker image
        run: docker build -t olx-crawler-app .

      - name: Criar diretório na VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: mkdir -p ~/app

      - name: Copiar arquivos para a VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          source: "build/libs/*.jar,Dockerfile,docker-compose.yml"
          target: "~/app"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            cd ~/app
            docker-compose down || true
            docker-compose up -d --build
